name: Bug Report
description: バグを報告する
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: バグの説明
      placeholder: 何が起きましたか？
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      placeholder: |
        1. ...
        2. ...
  - type: textarea
    id: expected
    attributes:
      label: 期待する動作
  - type: dropdown
    id: browser
    attributes:
      label: ブラウザ
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
        - その他
